In [1]:
import pandas as pd

In [2]:
arabica = pd.read_csv("./arabica_data_cleaned.csv")

In [18]:
arabica

,Unnamed: 0,Species,Owner,Country.of.Origin,Farm.Name,Lot.Number,Mill,ICO.Number,Company,Altitude,...,Color,Category.Two.Defects,Expiration,Certification.Body,Certification.Address,Certification.Contact,unit_of_measurement,altitude_low_meters,altitude_high_meters,altitude_mean_meters
0,1,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,...,Green,0,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.00,2200.00,2075.00
1,2,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,...,Green,1,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.00,2200.00,2075.00
3,4,Arabica,yidnekachew dabessa,Ethiopia,yidnekachew dabessa coffee plantation,NaN,wolensu,NaN,yidnekachew debessa coffee plantation,1800-2200,...,Green,2,"March 25th, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1800.00,2200.00,2000.00
4,5,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,...,Green,2,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.00,2200.00,2075.00
5,6,Arabica,ji-ae ahn,Brazil,NaN,NaN,NaN,NaN,NaN,NaN,...,Bluish-Green,1,"September 3rd, 2014",Specialty Coffee Institute of Asia,726e4891cf2c9a4848768bd34b668124d12c4224,b70da261fcc84831e3e9620c30a8701540abc200,m,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1306,1307,Arabica,juan carlos garcia lopez,Mexico,el centenario,NaN,"la esperanza, municipio juchique de ferrer, ve...",1104328663,terra mia,900,...,NaN,20,"September 17th, 2013",AMECAFE,59e396ad6e22a1c22b248f958e1da2bd8af85272,0eb4ee5b3f47b20b049548a2fd1e7d4a2b70d0a7,m,900.00,900.00,900.00
1307,1308,Arabica,myriam kaplan-pasternak,Haiti,200 farms,NaN,coeb koperativ ekselsyo basen (350 members),NaN,haiti coffee,~350m,...,Blue-Green,16,"May 24th, 2013",Specialty Coffee Association,36d0d00a3724338ba7937c52a378d085f2172daa,0878a7d4b9d35ddbf0fe2ce69a2062cceb45a660,m,350.00,350.00,350.00
1308,1309,Arabica,"exportadora atlantic, s.a.",Nicaragua,finca las mar√≠as,017-053-0211/ 017-053-0212,beneficio atlantic condega,017-053-0211/ 017-053-0212,exportadora atlantic s.a,1100,...,Green,5,"June 6th, 2018",Instituto Hondure√±o del Caf√©,b4660a57e9f8cc613ae5b8f02bfce8634c763ab4,7f521ca403540f81ec99daec7da19c2788393880,m,1100.00,1100.00,1100.00
1309,1310,Arabica,juan luis alvarado romero,Guatemala,finca el limon,NaN,beneficio serben,11/853/165,unicafe,4650,...,Green,4,"May 24th, 2013",Asociacion Nacional Del Caf√©,b1f20fe3a819fd6b2ee0eb8fdc3da256604f1e53,724f04ad10ed31dbb9d260f0dfd221ba48be8a95,ft,1417.32,1417.32,1417.32
1310,1312,Arabica,bismarck castro,Honduras,los hicaques,103,cigrah s.a de c.v.,13-111-053,cigrah s.a de c.v,1400,...,Green,2,"April 28th, 2018",Instituto Hondure√±o del Caf√©,b4660a57e9f8cc613ae5b8f02bfce8634c763ab4,7f521ca403540f81ec99daec7da19c2788393880,m,1400.00,1400.00,1400.00

In [11]:
arabica['Country.of.Origin'] = arabica['Country.of.Origin'].str.strip().str.title()
arabica['Harvest.Year'] = arabica['Harvest.Year'].str.strip()

In [14]:
# Replace any known anomalies in country names, e.g., 'Usa' to 'USA'
arabica['Country.of.Origin'] = arabica['Country.of.Origin'].replace({'Usa': 'USA', 'Uk': 'United Kingdom'})  # Add more replacements as needed

In [15]:
arabica.dropna(subset=['Country.of.Origin', 'Harvest.Year'], inplace=True)

In [17]:
# Convert Harvest Year to int if necessary, checking if there are non-numeric values first
arabica = arabica[pd.to_numeric(arabica['Harvest.Year'], errors='coerce').notna()]  # Removes non-numeric years
arabica['Harvest.Year'] = arabica['Harvest.Year'].astype(int)

/tmp/ipykernel_30004/1612894355.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  arabica['Harvest.Year'] = arabica['Harvest.Year'].astype(int)

In [19]:
ratings_columns = ['Aroma', 'Flavor', 'Aftertaste', 'Acidity', 'Body', 'Balance', 'Uniformity', 'Clean.Cup', 'Sweetness', 'Cupper.Points', 'Total.Cup.Points']

In [21]:
mean_ratings = arabica.groupby(['Country.of.Origin', 'Harvest.Year'])[ratings_columns].mean().reset_index()

In [22]:
mean_ratings

,Country.of.Origin,Harvest.Year,Aroma,Flavor,Aftertaste,Acidity,Body,Balance,Uniformity,Clean.Cup,Sweetness,Cupper.Points,Total.Cup.Points
0,Brazil,2010,8.295000,7.920000,7.960000,7.750000,8.125000,8.000000,10.000000,10.000000,10.000000,8.125000,86.170000
1,Brazil,2011,8.017143,7.929286,7.684286,7.726429,7.690714,7.737857,10.000000,10.000000,10.000000,7.732857,84.517857
2,Brazil,2012,7.625000,7.600000,7.408500,7.500500,7.508000,7.513000,9.966500,9.966500,9.966500,7.497000,82.550500
3,Brazil,2013,7.647500,7.627500,7.460000,7.625000,7.667500,7.832500,9.832500,9.832500,10.000000,7.542500,83.062500
4,Brazil,2014,7.451429,7.500000,7.488571,7.440000,7.512857,7.522857,9.904286,9.428571,9.904286,7.500000,81.655714
...,...,...,...,...,...,...,...,...,...,...,...,...,...
124,United States (Puerto Rico),2013,7.647500,7.540000,7.480000,7.602500,7.665000,7.647500,9.000000,9.665000,9.832500,7.647500,81.727500
125,Vietnam,2012,7.670000,7.665000,7.170000,7.330000,7.875000,7.250000,10.000000,10.000000,10.000000,7.545000,82.500000
126,Vietnam,2014,7.333333,7.443333,7.470000,7.500000,7.556667,7.473333,9.776667,10.000000,10.000000,7.973333,82.526667
127,Vietnam,2017,7.500000,7.335000,7.165000,7.455000,7.500000,7.955000,9.335000,10.000000,10.000000,7.415000,81.670000
128,Zambia,2014,7.670000,7.080000,7.420000,7.330000,7.750000,7.420000,10.000000,10.000000,10.000000,7.250000,81.920000

In [ ]:
mean_ratings.to_csv('processed_coffee_ratings_arabica.csv', index=False)